// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowsBtns: typeof import('./../src/components/ArrowsBtns.vue')['default']
    CategoriesSection: typeof import('./../src/components/CategoriesSection.vue')['default']
    ExperienceSection: typeof import('./../src/components/ExperienceSection.vue')['default']
    Footer: typeof import('./../src/components/Footer.vue')['default']
    FooterPart: typeof import('./../src/components/FooterPart.vue')['default']
    HeaderPart: typeof import('./../src/components/HeaderPart.vue')['default']
    HeroSection: typeof import('./../src/components/HeroSection.vue')['default']
    PopularDestinationsSection: typeof import('./../src/components/PopularDestinationsSection.vue')['default']
    ReviewsSection: typeof import('./../src/components/ReviewsSection.vue')['default']
    SubscribeSection: typeof import('./../src/components/SubscribeSection.vue')['default']
    TopDestinationsSection: typeof import('./../src/components/TopDestinationsSection.vue')['default']
  }
}
